### ISSUE TITLE
x = 'foo' x = 'bar' parsing

### ISSUE THREAD

**Issue by BenasPaulikas** [isaacs/ini#37] opened 2014-12-20 13:57 UTC
Hello, in my .ini file I have 

ServerPackages=Core
ServerPackages=Engine
....

After parsing it leaves only 1 ServerPackages line, how this can be fixed ?

**Comment by kodypeterson** [comment] 2015-01-11 23:06
I think it needs to be:

ServerPackages[]=Core
ServerPackages[]=Engine

This is the way ini's arrays seem to work

**Comment by BenasPaulikas** [comment] 2015-01-12 07:19
Yeah, it would be great but the .ini file is provided by other application, I know it's dumb to assign multiple values to the same "variable", if I do name[] = value1 name[] = value2 app isn't working.

**Comment by kodypeterson** [comment] 2015-01-13 17:31
I would suggest some sort of middle parser...

Something that would read the input add the [] and then pass it to the parser.

None the less probably not a problem with this library.

**Comment by BenasPaulikas** [comment] 2015-01-13 17:58
Can you reccommend such middle parser ? Or I should do it by hand like string.replace('ServerPackages','ServerPackages[]') ?

**Comment by hotamy** [comment] 2016-02-03 09:18
I have same problem ...
Have solution it?

**Comment by isaacs** [comment] 2016-02-13 07:09
Duplicate of https://github.com/isaacs/ini/issues/52

(Technically https://github.com/isaacs/ini/issues/52 is a duplicate of this, but that's more clearly stated, and probably @robertkowalski will give you what you want :)

**Closed by isaacs** 2016-02-13 07:09 UTC

**Comment by robertkowalski** [comment] 2016-02-25 00:21
see here: https://github.com/npm/ini/issues/52#issuecomment-188531495
